<!-- student-log (the root element) can contain one or more student elements-->
<!ELEMENT student-log (student)+>

<!-- student elements MUST contain a first name, last name, full contact info and academic info aside from their graduation date and minor. A student does not need a middle-name, preferred-name, minor, or graduation-date by design. Not all students have a middle or preferred name, not everyone gets a minor, and not everyone knows when they will graduate -->
<!ELEMENT student (first-name, middle-name?, last-name, preferred-name?, contact-info, status, academic-info)>
<!ELEMENT first-name (#PCDATA)>
<!ELEMENT middle-name (#PCDATA)>
<!ELEMENT last-name (#PCDATA)>
<!ELEMENT preferred-name (#PCDATA)>

<!-- id CDATA is a required field used to differentiate students from eachother. It's shown in the frontend through the css, using an [attr] field -->
<!ATTLIST student
          id CDATA #REQUIRED>

<!-- information related to contact-info -->
<!ELEMENT contact-info (email, phone)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT phone (#PCDATA)>

<!ELEMENT status EMPTY>
<!ATTLIST status
          enrollment (full-time | part-time | graduated | withdrawn) #REQUIRED
          year (first-year | second-year | third-year | fourth-year | graduate) #REQUIRED>

<!-- information related to academic-info -->
<!-- <!ELEMENT academic-info (status-year,gpa,major,minor?,status-enrollment,advisor,date-initial-enrollment,graduation-date?) -->
<!ELEMENT academic-info (gpa,major,minor?,advisor,date-initial-enrollment,graduation-date?)>

<!ELEMENT status-year (#PCDATA)>
<!ELEMENT gpa (#PCDATA)>
<!ELEMENT major (#PCDATA)>
<!ELEMENT minor (#PCDATA)>
<!ELEMENT status-enrollment (#PCDATA)>
<!ELEMENT advisor (#PCDATA)>
<!ELEMENT date-initial-enrollment (#PCDATA)>
<!ELEMENT graduation-date (#PCDATA)>
